version: "3.3"

services:
  database:
    container_name: database-blog-django
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=blogdjango  
      - POSTGRES_USER=blogdjango
      - POSTGRES_DB=blogdjango
    ports:
      - 5432:5432