# Generated by Django 4.0.3 on 2022-03-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutblog',
            old_name='about_blog',
            new_name='content',
        ),
    ]
